name: Test
on:
  workflow_dispatch:
    inputs:
      version:
        description: Additional version to include.
        required: false
        default: ""
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - run: test -e /usr/bin/luajit || echo No luajit.
    - uses: daaku/gh-action-apt-install@main
      with:
        packages: luajit
        version: ${{ github.event.inputs.version }}
    - run: test -e /usr/bin/luajit && echo Found luajit.
