name: Test
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: Additional version to include.
        required: false
        default: ""
jobs:
  test-luajit:
    name: Test LuaJIT
    runs-on: ubuntu-latest
    steps:
    - run: test -e /usr/bin/luajit || echo No luajit.
    - uses: daaku/gh-action-apt-install@main
      with:
        packages: luajit
        version: ${{ github.event.inputs.version }}
    - run: test -e /usr/bin/luajit && echo Found luajit.
  test-no-packages:
    name: Test No Packages
    runs-on: ubuntu-latest
    steps:
    - uses: daaku/gh-action-apt-install@main
      with:
        packages: dash
        version: ${{ github.event.inputs.version }}
